# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: "http://local.10degres.net"
host: "local.10degres.net"
port: 80